env:
  node: true
  es2021: true
extends: 
  - eslint:recommended
  - plugin:import/recommended
  - "airbnb-base"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: 0,
  import/extensions: 0
}